spring.application.name=StockMarket_CryptoSimulator
spring.datasource.username=postgres
spring.datasource.password=Baraa@123
spring.datasource.url=jdbc:postgresql://localhost:5432/StockCryptoDB
spring.jpa.hibernate.ddl-auto=update
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
logging.level.org.springframework.web=info
logging.level.org.hibernate.SQL=info

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437


